{
 "title": "VideoSys inference",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "benchmark description",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# VideoSys inference\n\nVideo diffusion framework used: [VideoSys](https://github.com/NUS-HPC-AI-Lab/VideoSys)\n\nModel used: [THUDM/CogVideoX-5b](https://huggingface.co/THUDM/CogVideoX-5b)\n\nThe `load-generator` container ramps the video generation requests with the folowing parameters:\n- prompt `batch_size` from 1 to 8 (limited by VRAM)\n- `num_inference_steps` from 20 to 100 in increment of 10\nTotal of 72 requests per pod.\n\nPayload example received by the `videosys-server`:\n```json\n{\n  \"prompt\": [\n      \"Sunset over the sea.\",\n      ] * batch_size,\n  \"num_inference_steps\": num_inference_steps,\n  \"seed\": -1,\n  \"cfg\": 6.5,\n  \"save_disk_path\": \"/results\"\n}\n```"
   }
  },
  {
   "title": "Request summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(videosys_inference:total_inference_steps_total{app=\"inference-benchmark-backend\"})",
     "legendFormat": "Total inference steps"
    },
    {
     "expr": "sum(videosys_inference:total_outputs_total{app=\"inference-benchmark-backend\"})",
     "legendFormat": "Total outputs generated"
    },
    {
     "expr": "avg(videosys_inference:bench_duration{app=\"inference-benchmark-backend\"})",
     "legendFormat": "Bencmark duration, s"
    }
   ]
  },
  {
   "title": "Request summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(videosys_inference:total_batch_attempts_total{app=\"inference-benchmark-backend\"})",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(videosys_inference:successful_batches_total{app=\"inference-benchmark-backend\"})",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "sum(videosys_inference:failed_batches_total{app=\"inference-benchmark-backend\"})",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Time per Inference Step (s)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (videosys_inference:tps_bucket{app=\"inference-benchmark-backend\"})",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Time per Batch Step (s)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (videosys_inference:tpb_bucket{app=\"inference-benchmark-backend\"})",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}