# Default values for inference-benchmark-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
servedModel: THUDM/CogVideoX-5b

image:
  pullPolicy: Always
  serverURI: ghcr.io/cyril-k/videosys-server
  serverTag: latest
  loadGeneratorURI: ghcr.io/cyril-k/load-generator-videosys
  loadGeneratorTag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: 
  prometheus.io/scrape: "true"
  # prometheus.io/port: "8080"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # privileged: true


service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []

hfToken: ""